# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17r_JrV6L3trKoYkFCNE0oIh3Im2zHm4g
"""

import pandas as pd





